// Here define all the action types


export const actionTypes = {
    'FETCH_ALL_FILTERS': 'FETCH_ALL_FILTERS',
    'TOGGLE_FILTER': "TOGGLE_FILTER",
    'SET_PRODUCTS': 'SET_PRODUCTS',
    'FILTER_EXPAND': 'FILTER_EXPAND',
    'FILTER_VIEW_MORE': 'FILTER_VIEW_MORE',
    'REMOVE_FILTERS': 'REMOVE_FILTERS',
    'SELECT_TAB': 'SELECT_TAB',
    'FETCH_FILTERED_PRODUCTS': 'FETCH_FILTERED_PRODUCTS',
    'UPDATE_SORTING': 'UPDATE_SORTING',
    'ADD_MORE_PRODUCTS': 'ADD_MORE_PRODUCTS',
    "ADD_TO_BAG": "ADD_TO_BAG",
    'CHANGE_QUANTITY': 'CHANGE_QUANTITY',
    'REMOVE_PRODUCTS': 'REMOVE_PRODUCTS'
}